In [1]:
# imagined speech, fig 3a, 1 prediction similarity to stimulus vs 1 prediction similaairity to incorrect stimulus, pairwise accuracy, can only classify, not significant

# no data yet for incorrect transcript's similarity

import numpy as np
import pandas as pd

scores = np.load('scores_bravo_ref_ims/S1/imagined_speech/bravo_repeat-1.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])
print(score_files['story_zscores'][('bravo', 'BERT')])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('bravo', 'WER'): np.float64(0.9448455153161456), ('bravo', 'BLEU'): np.float64(0.5936014213095933), ('bravo', 'METEOR'): np.float64(0.7035903578282815), ('bravo', 'BERT'): np.float32(1.207469)}
1.207469

In [2]:
zscores_df = pd.DataFrame({'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]})

to_add = {'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]}
for task in ['alpha','bravo', 'charlie', 'delta', 'echo']:
    for repeat in [1,2]:
        to_add['task'].append(f'{task}_repeat-{repeat}')
        for ref in ['alpha','bravo', 'charlie', 'delta', 'echo']:
            scores = np.load(f'scores_{ref}_ref_ims/S1/imagined_speech/{task}_repeat-{repeat}.npz', allow_pickle=True)
            # print(scores['story_zscores'].item()[(ref, 'BLEU')])
            to_add[f'{ref}_ref'].append(scores['story_zscores'].item()[(ref, 'BERT')])

zscores_df = pd.DataFrame(to_add)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   3.021082  -0.258895     0.151464   0.676137  0.334279
1    alpha_repeat-2   4.409098   2.651707     1.173889   2.337432  1.943111
2    bravo_repeat-1   0.521841   1.207469     0.174412   0.776450  0.635643
3    bravo_repeat-2   0.465184   1.974917     0.029757   0.492429 -0.397704
4  charlie_repeat-1   0.502385   0.638582     2.897635   1.853017  1.355776
5  charlie_repeat-2   1.683882   0.928268     2.849493   1.425145  2.647938
6    delta_repeat-1   0.958044   1.743529     1.499965   3.050910  3.198681
7    delta_repeat-2   1.162428   0.390275     2.630574   1.867975  0.944892
8     echo_repeat-1   3.093866   1.678933     0.937015   1.099240  4.177301
9     echo_repeat-2   0.018079   0.683202     2.390418   0.543208  2.331259

In [ ]:
zscores_df.to_csv('imagined_speech_zscores_S1.csv', index=False)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   3.021082  -0.258895     0.151464   0.676137  0.334279
1    alpha_repeat-2   4.409098   2.651707     1.173889   2.337432  1.943111
2    bravo_repeat-1   0.521841   1.207469     0.174412   0.776450  0.635643
3    bravo_repeat-2   0.465184   1.974917     0.029757   0.492429 -0.397704
4  charlie_repeat-1   0.502385   0.638582     2.897635   1.853017  1.355776
5  charlie_repeat-2   1.683882   0.928268     2.849493   1.425145  2.647938
6    delta_repeat-1   0.958044   1.743529     1.499965   3.050910  3.198681
7    delta_repeat-2   1.162428   0.390275     2.630574   1.867975  0.944892
8     echo_repeat-1   3.093866   1.678933     0.937015   1.099240  4.177301
9     echo_repeat-2   0.018079   0.683202     2.390418   0.543208  2.331259

In [4]:
results = np.load('results/S3/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

FileNotFoundError: [Errno 2] No such file or directory: 'results/S3/perceived_speech/wheretheressmoke.npz'