In [1]:
# imagined speech, fig 3a, 1 prediction similarity to stimulus vs 1 prediction similaairity to incorrect stimulus, pairwise accuracy, can only classify, not significant

# no data yet for incorrect transcript's similarity

import numpy as np
import pandas as pd

scores = np.load('scores_bravo_ref_ims/S2/imagined_speech/bravo_repeat-1.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])
print(score_files['story_zscores'][('bravo', 'BERT')])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('bravo', 'WER'): np.float64(-0.9997299691880507), ('bravo', 'BLEU'): np.float64(0.2935050854653309), ('bravo', 'METEOR'): np.float64(0.8340520762293799), ('bravo', 'BERT'): np.float32(3.4985328)}
3.4985328

In [2]:
zscores_df = pd.DataFrame({'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]})

to_add = {'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]}
for task in ['alpha','bravo', 'charlie', 'delta', 'echo']:
    for repeat in [1,2]:
        to_add['task'].append(f'{task}_repeat-{repeat}')
        for ref in ['alpha','bravo', 'charlie', 'delta', 'echo']:
            scores = np.load(f'scores_{ref}_ref_ims/S2/imagined_speech/{task}_repeat-{repeat}.npz', allow_pickle=True)
            # print(scores['story_zscores'].item()[(ref, 'BLEU')])
            to_add[f'{ref}_ref'].append(scores['story_zscores'].item()[(ref, 'BERT')])

zscores_df = pd.DataFrame(to_add)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   0.061905  -0.524385    -0.736597  -0.691199  0.974840
1    alpha_repeat-2   4.606549   0.648212     0.413959  -0.293938  1.370507
2    bravo_repeat-1   1.598937   3.498533     1.113266   0.385127  0.844503
3    bravo_repeat-2   1.941418   3.526081     1.037750   0.925051 -0.037259
4  charlie_repeat-1   1.288512   1.750442     6.056946   2.187703  2.061005
5  charlie_repeat-2   1.192603   1.915807     6.139088   1.862484  1.318124
6    delta_repeat-1   0.080015   1.240901     0.363888   2.816360  2.638196
7    delta_repeat-2   0.560297   0.482072     2.161670   4.049665  1.436602
8     echo_repeat-1   0.653130  -0.940910     0.295770   1.082029  1.686641
9     echo_repeat-2   1.472686   0.421925     1.660682   1.038557  4.999512

In [3]:
zscores_df.to_csv('imagined_speech_zscores.csv', index=False)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   0.061905  -0.524385    -0.736597  -0.691199  0.974840
1    alpha_repeat-2   4.606549   0.648212     0.413959  -0.293938  1.370507
2    bravo_repeat-1   1.598937   3.498533     1.113266   0.385127  0.844503
3    bravo_repeat-2   1.941418   3.526081     1.037750   0.925051 -0.037259
4  charlie_repeat-1   1.288512   1.750442     6.056946   2.187703  2.061005
5  charlie_repeat-2   1.192603   1.915807     6.139088   1.862484  1.318124
6    delta_repeat-1   0.080015   1.240901     0.363888   2.816360  2.638196
7    delta_repeat-2   0.560297   0.482072     2.161670   4.049665  1.436602
8     echo_repeat-1   0.653130  -0.940910     0.295770   1.082029  1.686641
9     echo_repeat-2   1.472686   0.421925     1.660682   1.038557  4.999512

In [4]:
results = np.load('results/S2/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

{'words': array(['i', "don't", 'have', ..., 'world', 'i', 'could'],
       shape=(1588,), dtype='<U12'),
 'times': array([ 10.2,  10.6,  11. , ..., 591. , 591.4, 591.8], shape=(1588,))}