In [1]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/perceived_speech/width_800/wheretheressmoke.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['window_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('wheretheressmoke', 'WER'): array([ 5.43344312e-01,  8.45947028e-01,  6.41970568e-01, -2.56682290e-01,
        6.96749926e-03, -2.90312763e-02,  1.89541316e-01,  7.87311593e-02,
        2.73760055e-01,  1.09748613e-01,  2.57749777e-01,  6.73327017e-01,
        1.08147685e+00,  7.34503068e-01,  2.12778625e-01,  3.08530454e-01,
        5.34430188e-01,  9.21359459e-01, -5.53205210e-01, -2.71562723e-01,
       -2.34692228e-01, -2.50453192e-01, -3.71521425e-01, -1.03084946e+00,
       -1.00009804e+00, -8.21902284e-01, -7.29295924e-01, -1.12597784e+00,
        2.45769576e-01,  1.53732763e+00,  1.30541958e+00,  8.76712329e-01,
        2.25820957e-01,  1.36102470e+00,  1.73908868e+00,  1.49002802e+00,
        1.74073093e+00,  2.17835240e+00,  9.72146782e-01,  1.39780778e+00,
        6.99317442e-01,  1.07850637e+00,  1.48652048e+00,  2.13831372e+00,
        3.11766488e+00,  3.74588350e+00,  4.27035788e+00,  4.40433812e+00,
        4.07690390e+00,  2.33162206e+00,  2.18073962e+00,  2.73945840e+00,
        1.85799267e+00,  3.42634461e+00,  4.49266068e+00,  6.42892882e+00,
        4.71746487e+00,  2.82325744e+00,  1.65234035e+00,  2.91547595e+00,
        3.19864140e+00,  2.66011952e+00,  3.31617119e+00,  1.30212333e+00,
        2.15286029e+00,  1.78202465e+00,  1.00174065e+00,  4.11165485e-01,
        6.06470531e-01,  3.17220634e-01, -3.63042597e-01, -1.06445521e-01,
       -1.10149945e+00, -1.27533670e+00, -1.17241891e+00, -8.13310862e-01,
       -5.85136102e-01, -7.14857404e-01, -7.12696645e-01, -6.76940524e-01,
       -3.19007836e-01,  3.83843545e-01, -1.12729339e+00, -4.68916502e-01,
        1.85372399e-01,  2.82901452e-01,  1.07211253e-01,  3.00139653e-01,
        2.00377576e-01,  9.23233315e-01, -1.93389080e-01,  4.18857582e-03,
       -4.13678232e-01,  3.55497064e-01,  5.21654062e-01,  6.07298040e-01,
        9.88872199e-01,  2.65810221e-02, -3.78339997e-01,  1.06957780e+00,
        1.48944866e+00,  2.30916125e+00,  2.64937547e+00,  2.57815249e+00,
        1.98481350e+00,  1.88760318e+00,  2.21469847e+00,  3.19650169e+00,
        2.63309593e+00,  2.63262861e+00,  2.59115249e+00,  3.33626783e+00,
        2.54635758e+00,  3.72920499e+00,  3.22165792e+00,  1.96939383e+00,
        2.57030185e+00,  3.54704536e+00,  2.56765896e+00,  3.38593103e+00,
        3.20143613e+00,  2.54274094e+00,  2.89912483e+00,  3.82068337e+00,
        4.79108380e+00,  4.75928697e+00,  4.36230478e+00,  3.72506459e+00,
        4.33226161e+00,  4.23762337e+00,  3.66186531e+00,  3.97733636e+00,
        2.39343071e+00,  3.02876997e+00,  2.88195806e+00,  2.84025335e+00,
        3.66224381e+00,  2.50011882e+00,  3.07453045e+00,  3.81465750e+00,
        4.44931720e+00,  3.58057334e+00,  2.66994180e+00,  4.58947177e-01,
        1.47864705e+00,  1.16090865e-01,  1.43052833e+00,  1.49583507e+00,
        8.39564379e-01,  7.99388411e-01,  1.28375995e+00,  1.10091781e+00,
        1.14750222e+00,  1.39103008e+00,  2.00680273e+00,  2.00468726e+00,
        2.01818131e+00,  1.10318691e+00,  2.25324413e+00,  2.97714740e+00,
        2.50276864e+00,  2.06879149e+00,  1.58165918e+00,  1.14679878e+00,
        1.52171743e+00,  1.33864708e+00,  1.78084189e+00,  2.33792413e+00,
        8.69420921e-01,  1.32615788e+00,  1.09241562e+00,  1.68396998e+00,
        1.89818603e+00,  1.36253177e+00, -1.06637065e+00, -2.25622069e-01,
       -7.73193242e-01,  3.01797273e-01,  3.91432973e-01, -3.64044429e-02,
       -2.31449301e-01,  8.37876782e-01,  5.14075930e-01,  2.14931177e+00,
        6.50792473e-01,  1.67384267e+00,  1.02553929e+00,  1.58924451e+00,
        1.00286124e+00,  1.25738693e+00,  1.61223607e+00,  6.82195066e-01,
        1.31778677e+00,  6.19368866e-01,  5.81958846e-01,  1.33025762e+00,
        1.70240901e+00,  1.08071948e+00,  1.30235252e+00,  8.72854814e-01,
       -1.32773699e-01,  9.79624889e-01, -1.44714921e-01,  5.93942301e-01,
        2.46913298e+00,  2.55830583e+00,  1.52325720e+00,  1.18148669e+00,
        2.57357950e+00,  1.01480470e+00,  1.72848324e+00,  1.66171589e+00,
        1.52870401e+00,  2.43147590e+00,  2.53895441e+00,  2.66751635e+00,
        2.33343974e+00,  1.65124551e+00,  1.12031530e+00,  9.92585035e-01,
        3.59823997e-01,  2.69170046e+00,  9.74222699e-01,  2.59059649e-01,
        5.12946334e-01,  1.95863757e+00, -1.04488820e-01, -4.45285744e-01,
        1.80173519e+00,  1.15041057e+00,  2.01748099e+00,  1.43381955e+00,
        5.47662554e-01,  1.12587711e+00,  2.47535106e+00,  1.08773054e+00,
        1.41021348e+00,  1.32107818e+00,  7.30772322e-01,  1.06956368e+00,
        9.03965502e-01, -3.78458534e-02,  7.02263527e-01,  5.44459919e-01,
        1.04103649e+00,  2.39447249e-01, -1.16726201e-01, -4.68183564e-01,
       -1.07957482e-01, -3.32909253e-01, -5.87136564e-01, -7.24866969e-01,
       -1.04490055e+00, -8.57632059e-01, -1.37696244e+00, -6.74737752e-01,
       -1.50926079e+00, -1.18245942e+00, -6.32018300e-01, -1.35444547e+00,
       -1.75341612e+00, -1.56145032e+00, -1.81887474e+00, -1.71013299e+00,
       -3.95673841e-01,  2.55492698e-01, -2.04876921e+00, -1.21298497e+00,
       -5.24758657e-01,  1.39503690e+00,  4.23939857e-01,  6.18718434e-01,
       -1.07843904e-01,  3.55677278e-01, -1.11041827e-02,  7.99179199e-01,
        4.82635507e-01,  1.19590489e+00,  1.27598617e+00,  1.47391105e+00,
        2.33002282e+00,  2.28174571e+00,  2.06740689e+00,  1.37082112e+00,
        1.46025132e+00,  1.58596742e+00,  1.34047428e+00,  1.55917202e+00,
        1.75899386e+00,  1.63702880e+00,  1.13620013e+00,  1.80762278e+00,
        2.40785384e+00,  1.74741106e+00,  1.36225306e+00,  4.32513035e-01,
        1.43925798e+00,  2.53179578e+00,  1.84897308e+00,  2.00265646e+00,
        2.17815918e+00,  1.53029424e+00,  2.89452773e+00,  2.04516017e+00,
        6.26782498e-01,  1.01126427e+00,  2.21278611e+00,  2.17346871e+00,
        2.40602728e+00,  2.48640139e+00,  3.87591845e+00,  4.42505091e+00,
        3.11705326e+00,  2.16657267e+00,  3.52953291e+00,  1.77892077e+00,
        2.23385617e+00,  1.01570189e+00,  9.64822165e-01,  5.89067922e-01,
        8.91314227e-01, -3.24599920e-01, -2.04325415e-01, -1.88480349e-01,
        5.70114701e-01,  7.84314340e-01,  8.54357658e-02,  4.47661481e-02,
        4.06138466e-01,  1.26618310e-01,  7.70256547e-02,  3.94225282e-02,
        9.47466468e-02,  1.98631177e+00,  1.95008725e+00,  1.53167423e+00,
        1.68222139e+00,  1.62532624e+00,  1.05879101e+00,  1.41479066e+00,
        1.86572623e+00,  1.90414218e+00,  3.23725633e+00,  2.06442070e+00,
        4.80096029e-01,  9.08646417e-01,  1.30745295e+00,  1.56588125e+00,
        1.33468810e+00,  1.27047130e+00,  2.97418017e-01,  6.46095738e-01,
        1.68699112e+00,  9.69285271e-02, -2.39106365e-01,  1.50372557e-01,
        1.97766378e-01, -9.09107946e-02, -1.66083012e-01,  3.17686639e-02,
        1.00593748e+00,  1.98970365e+00,  8.82843113e-01,  1.47557684e+00,
        8.90427875e-01,  9.89949494e-01,  1.02934186e+00,  1.61974699e+00,
        2.14308171e+00,  2.26779775e+00,  1.80113282e+00,  1.15011771e+00,
        1.93126575e+00,  1.95103587e+00,  2.61699813e+00,  3.30591446e+00,
        3.11404641e+00,  3.81187636e+00,  3.04449073e+00,  3.30183486e+00,
        2.79700236e+00,  3.22653667e+00,  3.33623062e+00,  4.28247856e+00,
        3.92940445e+00,  4.75722527e+00,  4.09521657e+00,  2.67580639e+00,
        2.79839460e+00,  3.51634190e+00,  3.58341371e+00,  2.76066321e+00,
        2.37180237e+00,  2.07287016e+00,  3.34322779e+00,  1.85970955e+00,
        2.05090284e+00,  1.29736387e+00,  1.02608100e+00,  1.16998106e+00,
        2.17970537e+00,  1.53324821e+00,  1.34877464e+00,  1.86107436e+00,
        2.20297085e+00,  2.84079851e+00,  3.28972552e+00,  3.69087460e+00,
        2.28667868e+00,  1.61997176e+00,  2.83865915e+00,  3.67918757e+00,
        3.49607803e+00,  3.75159541e+00,  3.56748576e+00,  3.18166477e+00,
        2.82653584e+00,  3.47066864e+00,  3.66461206e+00,  3.77257181e+00,
        4.31420153e+00,  3.80956983e+00,  3.95835431e+00,  4.57257576e+00,
        2.13721563e+00,  1.81575189e+00,  3.05814265e+00,  2.53675659e+00,
        2.19254760e+00,  1.87411397e+00,  1.40564160e+00,  1.41170693e+00,
        9.55109099e-01,  1.31049277e+00,  2.04294462e-01,  5.52325327e-01,
        9.44727829e-02,  3.95549561e-01, -3.33518673e-02,  6.35026764e-02,
       -1.62594181e+00, -2.04866471e-01, -8.72255180e-01, -7.06649185e-01,
        8.83044410e-01,  7.34456278e-01,  5.38815906e-01,  1.39808197e-01,
        5.56843033e-01,  3.27543536e-01,  4.30084450e-01,  1.29692601e+00,
        6.69434392e-01,  8.56611573e-02,  3.36752226e-01,  1.23928583e+00,
        1.26812980e+00,  9.37343436e-01,  8.46202783e-01,  1.59639515e+00,
        1.70001502e+00,  2.16921907e+00,  1.70444648e+00,  1.68187946e+00,
        9.74293343e-01,  9.89969977e-01,  6.04729565e-01,  7.69493487e-01,
        1.54111603e+00,  2.17115029e+00,  2.51900907e+00,  1.94752728e+00,
        2.36461024e+00,  3.25790919e+00,  2.79189279e+00,  1.89684144e+00,
        2.42424124e+00,  3.22510879e+00,  2.69850234e+00,  2.19222664e+00,
        3.15372066e+00,  3.24678578e+00,  3.40017760e+00,  4.63377925e+00,
        4.75498311e+00,  5.28445119e+00,  3.97038042e+00,  3.96493252e+00,
        3.16431231e+00,  1.75666963e+00,  1.61984632e+00,  2.26147291e+00,
        1.74513783e+00,  1.38250316e+00,  5.63171087e-01,  6.89283264e-01,
        2.30065207e+00,  2.02320146e+00,  1.68766392e+00,  1.58244560e+00,
        1.15044748e+00, -1.86475715e-01, -4.49644554e-01, -8.01007291e-01,
       -1.07493794e+00, -1.01786369e+00, -3.90391658e-01, -4.34586121e-01,
       -2.07792909e-01, -4.78254377e-01,  1.85695338e-01, -1.58473028e+00,
       -1.56208630e+00, -1.12884613e+00,  1.45180176e-01, -3.95746835e-02,
       -3.24439357e-02, -1.15950181e+00, -1.14732955e+00, -7.39881659e-02,
        8.06697525e-01,  2.02389249e-01,  1.22157879e+00,  1.49257883e+00,
        4.67217906e-01,  9.41799315e-01, -4.30730492e-02,  1.04589789e+00,
        7.61938390e-01,  7.86980999e-01,  1.00713322e-01,  1.19857900e+00,
        1.25023781e+00,  2.19705146e+00,  3.13169051e+00,  3.43728131e+00,
        3.19398857e+00,  2.27721928e+00,  3.07655794e+00,  1.06341014e+00,
        1.34288319e+00,  1.85893287e-01, -6.03308347e-02, -5.26234812e-01,
        6.72451730e-02,  1.88422288e-01,  6.53414507e-01,  1.32396409e+00,
        9.02337291e-01,  1.05690592e+00,  9.95565388e-01,  1.63239941e-01,
        1.18091145e+00,  1.10783704e+00, -7.07759159e-01,  2.43135723e-01,
        1.65872201e-01, -2.25934619e-02,  4.75571471e-01, -3.79987082e-01,
       -3.40724642e-01, -2.94330928e-01, -4.46020494e-01]), ('wheretheressmoke', 'BLEU'): array([ 0.41985921,  0.31083754,  0.21915425,  0.13200131,  0.24134422,
        0.2285818 ,  0.53933389,  0.25317216, -0.43892216,  0.02313449,
       -0.03396372, -0.36078458,  0.22479292,  0.41023687, -0.03260135,
       -0.12781307,  0.21643649,  0.81740191,  0.36680319,  0.67369496,
        0.89354539,  1.41397993,  1.74688952,  1.75149333,  1.55638173,
        1.20354043,  0.84586436,  0.73188356,  0.23246844,  0.2397696 ,
        0.57488121,  0.92531235,  2.46130149,  2.16762433,  2.46347843,
        2.12976668,  2.14024118,  1.68696586,  2.16508591,  1.8838155 ,
        1.44089861,  1.19440968,  1.51599425,  1.39779851,  1.98453708,
        2.02205745,  2.50392702,  2.95748137,  3.02913244,  3.07872773,
        3.06167032,  2.8020439 ,  2.42313451,  2.24355588,  2.36420116,
        2.83954182,  2.84042244,  2.89139924,  3.52330478,  3.43333566,
        3.49401915,  4.09304847,  2.80613865,  1.61424946,  1.83483971,
        1.14501081,  0.83333333,  0.58156468,  0.74741784,  1.21538425,
        0.94149222,  0.01183204, -0.66512394, -0.92115528, -1.28345602,
       -1.28345602, -1.28345602, -0.63642489, -0.74466871, -1.29769668,
       -1.6429604 , -2.02156513, -2.1558836 , -1.79065228, -1.16352596,
       -0.53214448, -0.41908169,  0.48112137,  0.54520487,  0.00712037,
        0.72806651,  0.46782653,  0.52883965,  0.52275824,  0.57543769,
        1.03251905,  0.6014713 ,  0.61518824,  0.10421683,  0.54997972,
        0.71980066,  1.41899727,  1.00701806,  1.57046528,  1.2101539 ,
        1.41662218,  1.77855151,  2.14834243,  1.98917412,  2.77342728,
        3.58328801,  4.40774668,  4.59141275,  3.973831  ,  4.00617778,
        3.32723301,  3.17077141,  2.74827683,  2.99028957,  3.27943757,
        3.34984106,  3.1958205 ,  3.00989242,  3.74175692,  3.37373045,
        3.3168366 ,  2.30244718,  2.50471202,  2.44563337,  2.31708282,
        1.97853445,  1.95472709,  2.05898963,  2.12200952,  1.99556029,
        1.88309243,  1.99161123,  1.67096563,  1.33940243,  1.15219913,
        1.1757927 ,  0.73399123,  1.27326665,  0.19556476,  0.73909509,
        0.35612714,  0.1410731 ,  0.27407964,  1.47553996,  1.46525182,
        1.68070996,  1.24604065,  1.51528377,  1.0597311 ,  1.77078299,
        0.9025513 ,  0.9330238 ,  1.07007215,  0.84297703,  0.63897326,
        0.49555855,  0.71872702,  0.55051166,  0.49789963,  0.91722201,
        1.30681106,  0.95542491,  0.35483614,  0.98264263,  0.70702716,
        1.39943704,  0.91437088,  0.65127836,  1.30425193,  0.8241284 ,
        1.16650858,  0.57735027,  1.60812419,  1.53882949,  2.17285791,
        1.92572911,  2.26260914,  2.12495201,  2.64575131,  1.87379849,
        2.19140761,  1.86760995,  1.93635758,  2.04166667,  2.18462247,
        2.86670859,  2.61739267,  3.64185284,  3.33443595,  2.99069281,
        2.17594897,  1.79607525,  2.07015142,  2.14267848,  2.1993596 ,
        2.12633557,  2.61311548,  2.58244205,  3.33987534,  3.85667344,
        4.23082129,  2.98400445,  2.535331  ,  2.05606752,  1.981549  ,
        1.63574927,  1.04166397,  1.14748113,  1.64839205,  2.22786117,
        2.60661634,  2.74093309,  2.78437627,  2.90686382,  3.20714145,
        2.57711742,  3.14347101,  3.12468718,  3.22429194,  3.257201  ,
        3.20116454,  2.51599946,  2.8469864 ,  2.07074137,  2.38426591,
        3.09582072,  3.15062308,  1.5938445 ,  1.89606827,  2.28197948,
        1.03576414,  0.87281718,  1.30881477,  1.32833332,  1.1612163 ,
        1.78474755,  1.09716871,  1.37470874,  1.3364976 ,  0.98984369,
        1.10241388,  0.96102852,  0.78311424,  0.29709872,  0.13517433,
       -0.61492459, -0.77189822, -1.03069309, -1.18486705, -1.82149525,
       -1.68717673, -2.41797412, -2.39080061, -2.63479652, -2.83317106,
       -2.4447982 , -1.90064227, -1.91169476, -1.93042415, -1.28910044,
       -1.27716198, -0.87064725, -0.9401114 , -0.48451686,  0.09703465,
       -0.80490451, -0.13837379, -0.31341766,  0.26551634,  0.43461651,
        0.54046345,  0.74359577,  1.14000005,  0.70312606,  0.84279864,
        1.52997281,  1.65353187,  0.90844988,  1.11877812,  1.39001388,
        1.01269907,  1.06697058,  0.93126615,  0.881906  ,  0.89035705,
        0.73547753,  0.56940921,  0.37917136,  0.4573384 ,  0.98117303,
        0.65824263,  1.01327393,  0.98586042,  1.5729154 ,  2.23749604,
        3.19598458,  3.79319122,  4.18518188,  4.10842568,  3.5878038 ,
        3.44565564,  4.1370474 ,  4.14716927,  3.87138005,  4.14125598,
        3.43222105,  2.78407864,  1.52856101,  0.78058127,  1.39804863,
        1.80131384,  1.34796224,  0.89151442,  0.57217025,  0.61436105,
        0.41511095, -0.01418997,  0.14728101,  0.09824857,  0.51421406,
        0.88859968,  0.23934479,  0.95129856,  0.58191662,  0.32808604,
        0.53966034,  1.23499396,  1.41618728,  1.58396819,  1.14662109,
        1.47010801,  1.46514505,  1.07724536,  0.82811628,  0.22610782,
        0.06386761, -0.21759674,  0.12291702,  0.31301926, -0.02801659,
       -0.48293148, -0.05235961, -0.55044446,  0.34394356,  0.94997367,
        0.50846183,  0.87208153,  0.74817752,  1.07574966,  1.05703493,
        0.84033163,  1.61855642,  1.68486673,  1.45835218,  1.70026287,
        1.43350109,  1.28867906,  1.35784223,  1.45189136,  0.76841217,
        0.6155358 ,  0.85567742,  0.6581844 ,  0.95069347,  0.98912489,
        0.77858085,  1.47848133,  1.41790363,  0.87046277,  1.17541305,
        2.03295509,  1.82505463,  2.10908202,  2.30490803,  2.46257194,
        2.77509252,  2.32410362,  2.03532406,  1.65955429,  2.11691682,
        2.43733339,  2.4446879 ,  1.74200389,  1.30165237,  1.91886256,
        1.63524712,  1.61155897,  0.86941954,  0.60476396,  1.1874118 ,
        0.99765003,  0.5074318 ,  0.64808357,  0.55941223,  0.32863353,
       -0.02830819,  0.68792703,  0.98403916,  1.37526644,  1.13425559,
        1.36877867,  0.68914603,  0.92463126,  0.93177401,  1.42570969,
        1.26449814,  1.63202987,  1.93676988,  2.30364137,  1.71482887,
        2.11809917,  2.16550134,  2.51107933,  2.44756869,  2.60492337,
        2.93320323,  3.27051129,  3.13676748,  2.7266289 ,  2.5426186 ,
        1.98834034,  2.34838351,  2.37958788,  1.8356149 ,  0.63743457,
        1.28803525,  0.65099271,  0.28532874,  0.47086073,  0.26628597,
       -0.07114977, -1.03116268, -0.61533967, -0.27646541,  0.05747886,
       -0.31660072, -0.09538373, -0.26042194, -0.58009446, -0.27541132,
       -0.14647571,  0.07189808,  0.22564906,  0.50484503,  0.23111044,
        0.3204127 ,  0.7208475 ,  0.77799109,  1.8392532 ,  1.71450152,
        2.36590827,  2.77905922,  3.36909636,  3.44340874,  3.03256155,
        2.09540356,  1.84941452,  1.89829388,  1.29239462,  0.81368986,
        0.67451503,  0.70782899,  0.90661473,  1.48195963,  1.43182015,
        1.95009751,  1.92638785,  2.3800714 ,  2.48020999,  2.41725575,
        1.71070248,  1.49683667,  0.87276038,  0.97749912,  0.76691535,
        1.51401129,  1.46306255,  1.31243484,  0.95147873,  1.15700413,
        0.64834818,  0.72159746,  0.88269237,  0.5787282 , -0.49924586,
       -0.24725379, -0.07370123,  0.26713763,  0.05412551,  0.09933409,
       -0.14927443,  0.70251266,  0.28995404,  0.71461846,  0.57235581,
        0.0650186 , -0.33402133, -0.4277538 , -0.34408827,  0.12897866,
        0.37986859,  0.40004735, -0.45057756, -0.2470243 , -0.66547949,
       -0.92106373, -1.03572273, -1.07079021,  0.0638983 ,  0.51501736,
        0.2240833 ,  0.58487094,  1.55185916,  0.77930014,  1.82003643,
        1.00537783,  0.69242476,  0.95476428,  0.9896834 ,  1.32463809,
        0.97337009,  1.57973642,  1.62791467,  1.28552121,  1.19919077,
        1.25177759,  1.7075742 ,  1.42685014,  1.85150259,  2.13152424,
        1.77403845,  2.11304321,  2.27621778,  1.73013802,  1.63379204,
        1.05665083,  1.06127711,  0.70544182,  1.60069413,  1.85718659,
        1.78227657,  1.49621617,  1.48123968,  1.28353396,  1.06458129,
        0.9284972 ,  1.45915375,  1.04948046,  0.82176042,  0.84558553,
        0.75669011,  0.24620414,  0.17968418,  0.87287156,  1.33120946,
        1.3521343 ,  0.84191223,  0.4995299 ]), ('wheretheressmoke', 'METEOR'): array([ 5.57462431e-01,  4.92663165e-01,  3.91916713e-01,  1.09758796e+00,
        1.07116441e+00,  6.60873426e-01,  1.62901705e-01,  3.60467952e-02,
       -2.69568457e-01,  7.19891729e-04,  7.57272477e-01, -4.22587385e-01,
       -1.07856535e-01,  2.74781273e-01, -1.94979918e-02, -2.21612615e-01,
       -7.45269985e-02,  8.91971552e-01,  7.82605660e-01,  7.25762304e-01,
        9.44117060e-01,  1.67488667e+00,  1.18592196e+00,  8.04930529e-01,
        2.99252364e-01,  1.50934844e-01, -3.16211250e-01, -3.39719183e-01,
        5.95951707e-01,  4.20824635e-01,  5.69176496e-01,  1.17750171e+00,
        2.17685577e+00,  1.95767700e+00,  2.14485630e+00,  1.72636693e+00,
        2.38380775e+00,  2.11400853e+00,  1.80347873e+00,  9.56452475e-01,
        6.05846648e-01,  1.57743393e-01,  3.28509350e-01,  1.01629240e+00,
        1.48163792e+00,  2.18109868e+00,  2.70067255e+00,  2.30089602e+00,
        2.29477070e+00,  2.26893213e+00,  1.72165293e+00,  1.44796392e+00,
        1.38770319e+00,  1.64589150e+00,  1.88254323e+00,  2.20095429e+00,
        2.29588654e+00,  2.28494414e+00,  4.01577438e+00,  3.00224751e+00,

In [2]:
window_zscores = {'subject': [], 'beam_width': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}

for j in [100, 200, 400, 800, 1600]:
    for subject in [1,2,3]:
        for task in ['wheretheressmoke']:
            scores = np.load(f'scores/S{subject}/perceived_speech/width_{j}/{task}.npz', allow_pickle=True)['window_zscores'].item()
            # print(scores['window_zscores'].item())
            window_zscores['subject'].append(subject)
            window_zscores['beam_width'].append(j)
            window_zscores['WER'].append(scores[(task, 'WER')])
            window_zscores['BLEU'].append(scores[(task, 'BLEU')])
            window_zscores['METEOR'].append(scores[(task, 'METEOR')])
            window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores.keys()

dict_keys(['subject', 'beam_width', 'WER', 'BLEU', 'METEOR', 'BERT'])

In [3]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

563
563
563
=
1689

,subject,beam_width,WER,BLEU,METEOR,BERT
0,1,100,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,2,100,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,3,100,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,1,200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,2,200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,3,200,"[0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..."
6,1,400,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,2,400,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,3,400,"[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
9,1,800,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
10,2,800,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
11,3,800,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
12,1,1600,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
13,2,1600,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
14,3,1600,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."

In [4]:
results_df

,subject,beam_width,WER,BLEU,METEOR,BERT
0,1,100,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,2,100,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,3,100,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,1,200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,2,200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,3,200,"[0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..."
6,1,400,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,2,400,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,3,400,"[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
9,1,800,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
10,2,800,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
11,3,800,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
12,1,1600,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
13,2,1600,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
14,3,1600,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."

In [5]:
# S1=np.array(results_df.loc[0, 'BERT']).mean()
# S2=np.array(results_df.loc[1, 'BERT']).mean()
# S3=np.array(results_df.loc[2, 'BERT']).mean()
# to_file = pd.DataFrame({'subject':[1,2,3], 'significantly_decoded': [S1,S2,S3]})
tocsv = results_df.drop(columns=['WER', 'BLEU', 'METEOR'])

tocsv['BERT'] = tocsv['BERT'].apply(lambda x : x.count(1)/len(x))

tocsv.to_csv('beam_width_sig_decoded.csv', index=False)

tocsv

    subject  beam_width      BERT
0         1         100  0.694494
1         2         100  0.591474
2         3         100  0.742451
3         1         200  0.571936
4         2         200  0.616341
5         3         200  0.740675
6         1         400  0.609236
7         2         400  0.603908
8         3         400  0.747780
9         1         800  0.689165
10        2         800  0.623446
11        3         800  0.763766
12        1        1600  0.678508
13        2        1600  0.699822
14        3        1600  0.799290

In [6]:
results = np.load('results/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

FileNotFoundError: [Errno 2] No such file or directory: 'results/S1/perceived_speech/wheretheressmoke.npz'