In [10]:
# imagined speech, fig 3a, 1 prediction similarity to stimulus vs 1 prediction similaairity to incorrect stimulus, pairwise accuracy, can only classify, not significant

# no data yet for incorrect transcript's similarity

import numpy as np
import pandas as pd

scores = np.load('scores_bravo_ref_ims/S1/imagined_speech/bravo_repeat-1.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])
print(score_files['story_zscores'][('bravo', 'BERT')])

FileNotFoundError: [Errno 2] No such file or directory: 'scores_bravo_ref_ims/S1/imagined_speech/bravo_repeat-1.npz'

In [ ]:
zscores_df = pd.DataFrame({'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]})

to_add = {'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]}
for task in ['alpha','bravo', 'charlie', 'delta', 'echo']:
    for repeat in [1,2]:
        to_add['task'].append(f'{task}_repeat-{repeat}')
        for ref in ['alpha','bravo', 'charlie', 'delta', 'echo']:
            scores = np.load(f'scores_{ref}_ref_ims/S1/imagined_speech/{task}_repeat-{repeat}.npz', allow_pickle=True)
            # print(scores['story_zscores'].item()[(ref, 'BLEU')])
            to_add[f'{ref}_ref'].append(scores['story_zscores'].item()[(ref, 'BERT')])

zscores_df = pd.DataFrame(to_add)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   0.907981   0.062857    -0.537885  -0.269528  0.381362
1    alpha_repeat-2   4.070785   1.444806     1.287158   0.300432  1.741888
2    bravo_repeat-1  -0.033774   2.548145     0.939911   0.666097  0.129651
3    bravo_repeat-2   0.226113   2.908008     1.078757   0.604345 -0.269690
4  charlie_repeat-1   0.535275   1.818745     4.217968   2.494092  0.826325
5  charlie_repeat-2   1.161186   1.907710     3.997573   1.690361  1.859481
6    delta_repeat-1  -0.029497  -0.146395     0.224024   3.869068  0.901875
7    delta_repeat-2   1.088162   1.066855     1.928483   3.831484  2.358587
8     echo_repeat-1   0.889443  -1.012097     0.922035   0.580298  1.543549
9     echo_repeat-2   2.056234   0.947409     1.927527   1.275707  4.527720

In [ ]:
zscores_df.to_csv('imagined_speech_zscores_S1.csv', index=False)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   0.907981   0.062857    -0.537885  -0.269528  0.381362
1    alpha_repeat-2   4.070785   1.444806     1.287158   0.300432  1.741888
2    bravo_repeat-1  -0.033774   2.548145     0.939911   0.666097  0.129651
3    bravo_repeat-2   0.226113   2.908008     1.078757   0.604345 -0.269690
4  charlie_repeat-1   0.535275   1.818745     4.217968   2.494092  0.826325
5  charlie_repeat-2   1.161186   1.907710     3.997573   1.690361  1.859481
6    delta_repeat-1  -0.029497  -0.146395     0.224024   3.869068  0.901875
7    delta_repeat-2   1.088162   1.066855     1.928483   3.831484  2.358587
8     echo_repeat-1   0.889443  -1.012097     0.922035   0.580298  1.543549
9     echo_repeat-2   2.056234   0.947409     1.927527   1.275707  4.527720

In [ ]:
results = np.load('results/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

{'words': array(['she', 'said', 'she', ..., 'that', 'she', 'needs'],
       shape=(1589,), dtype='<U13'),
 'times': array([ 10.2,  10.6,  11. , ..., 591. , 591.4, 591.8], shape=(1589,))}