In [5]:
# imagined speech, fig 3a, 1 prediction similarity to stimulus vs 1 prediction similaairity to incorrect stimulus, pairwise accuracy, can only classify, not significant

# no data yet for incorrect transcript's similarity

import numpy as np
import pandas as pd

scores = np.load('scores_bravo_ref_ims/S3/imagined_speech/bravo_repeat-1.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])
print(score_files['story_zscores'][('bravo', 'BERT')])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('bravo', 'WER'): np.float64(1.9715333719254102), ('bravo', 'BLEU'): np.float64(-0.5399228026051487), ('bravo', 'METEOR'): np.float64(-0.5358828865487915), ('bravo', 'BERT'): np.float32(1.1867886)}
1.1867886

In [6]:
zscores_df = pd.DataFrame({'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]})

to_add = {'task':[], 'alpha_ref':[],'bravo_ref':[],'charlie_ref':[], 'delta_ref':[], 'echo_ref':[]}
for task in ['alpha','bravo', 'charlie', 'delta', 'echo']:
    for repeat in [1,2]:
        to_add['task'].append(f'{task}_repeat-{repeat}')
        for ref in ['alpha','bravo', 'charlie', 'delta', 'echo']:
            scores = np.load(f'scores_{ref}_ref_ims/S3/imagined_speech/{task}_repeat-{repeat}.npz', allow_pickle=True)
            # print(scores['story_zscores'].item()[(ref, 'BLEU')])
            to_add[f'{ref}_ref'].append(scores['story_zscores'].item()[(ref, 'BERT')])

zscores_df = pd.DataFrame(to_add)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   0.936518  -0.448606    -0.800353  -0.115361 -0.311587
1    alpha_repeat-2   1.590507   0.896441     0.205996   0.807927  0.705488
2    bravo_repeat-1  -0.407443   1.186789    -0.468002  -1.017974 -0.651665
3    bravo_repeat-2  -1.270426   1.758270     0.638863  -0.771232 -0.489471
4  charlie_repeat-1   0.162730   0.902963     3.315383   2.241443  1.560014
5  charlie_repeat-2   0.700331   1.556649     2.677264   1.238296  0.820318
6    delta_repeat-1   0.250184   1.372677     0.917863   3.430859  0.920041
7    delta_repeat-2   1.212121   0.319779     0.946002   1.896280  0.970735
8     echo_repeat-1   1.180571  -0.598222     0.731890   0.435621  3.026317
9     echo_repeat-2   2.191342   2.364597     1.386640   1.102151  2.735279

In [7]:
zscores_df.to_csv('imagined_speech_zscores_S3.csv', index=False)

zscores_df

               task  alpha_ref  bravo_ref  charlie_ref  delta_ref  echo_ref
0    alpha_repeat-1   0.936518  -0.448606    -0.800353  -0.115361 -0.311587
1    alpha_repeat-2   1.590507   0.896441     0.205996   0.807927  0.705488
2    bravo_repeat-1  -0.407443   1.186789    -0.468002  -1.017974 -0.651665
3    bravo_repeat-2  -1.270426   1.758270     0.638863  -0.771232 -0.489471
4  charlie_repeat-1   0.162730   0.902963     3.315383   2.241443  1.560014
5  charlie_repeat-2   0.700331   1.556649     2.677264   1.238296  0.820318
6    delta_repeat-1   0.250184   1.372677     0.917863   3.430859  0.920041
7    delta_repeat-2   1.212121   0.319779     0.946002   1.896280  0.970735
8     echo_repeat-1   1.180571  -0.598222     0.731890   0.435621  3.026317
9     echo_repeat-2   2.191342   2.364597     1.386640   1.102151  2.735279

In [8]:
results = np.load('results/S3/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

{'words': array(['we', 'got', 'in', ..., 'me', 'we', 'are'],
       shape=(1598,), dtype='<U12'),
 'times': array([ 10.2,  10.6,  11. , ..., 591. , 591.4, 591.8], shape=(1598,))}