In [1]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['window_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('wheretheressmoke', 'WER'): array([ 6.25055987e-01,  1.54919334e+00,  1.45774958e+00,  1.33936787e+00,
        1.69937152e+00,  1.61598135e+00,  2.00698861e+00,  1.73152978e+00,
        3.03979376e-01,  1.22500941e-01,  1.06644164e+00,  1.39585843e+00,
        1.81772642e+00,  1.52208010e+00,  9.74185538e-01,  1.04293630e+00,
        3.00865336e-01,  1.58554873e+00,  1.28073887e+00,  1.87501316e+00,
        1.86308593e+00,  7.68941313e-01,  8.31715849e-01,  1.14841431e+00,
        1.20650193e+00,  1.09089769e+00,  2.64386351e-01,  1.59810329e+00,
        1.19344456e+00,  1.62649485e+00,  1.43543122e+00,  1.58586736e+00,
        9.67986391e-01,  1.25797850e+00,  1.51289998e+00,  1.35976906e+00,
        1.68766392e+00,  1.35987570e+00,  9.37911840e-01,  1.17932485e+00,
        1.76532044e-01,  3.83123063e-01,  3.65392048e-02, -1.23869628e-15,
        1.62606351e-01,  1.31032835e+00,  1.10288853e+00,  6.97588692e-01,
        1.13346614e+00, -4.98630023e-01,  1.39808197e-01,  2.86038777e-01,
        1.25989658e+00,  9.65616396e-01,  2.37329370e+00,  3.01791061e+00,
        1.99054885e+00,  3.43849745e-01,  1.82559330e+00,  1.16367751e+00,
        2.52575390e+00,  1.87926046e+00,  2.61974748e+00,  1.28002090e+00,
        2.24397376e+00,  7.87769151e-01,  1.03090821e+00,  1.44460730e+00,
       -4.77387823e-01, -4.02801830e-01, -2.63285915e-01, -7.93361657e-01,
       -9.00949146e-01, -9.62606157e-01, -8.78142042e-01, -5.90828076e-01,
       -4.53413450e-01,  2.67302382e-01, -5.27397993e-01,  3.44799547e-01,
        8.49110463e-01,  5.46812908e-01,  8.36973951e-02, -3.54222886e-01,
        3.93189986e-01,  1.23098144e+00,  1.04584241e+00,  1.28975879e+00,
        1.11921405e+00,  1.98315562e+00,  2.37332110e+00,  1.96643815e+00,
        3.05390934e+00,  3.93415591e+00,  4.16787907e+00,  3.40612609e+00,
        3.56929658e+00,  3.78333855e+00,  2.67973795e+00,  1.02435811e+00,
        1.46381975e+00,  1.59424090e+00,  1.92011426e+00,  1.75228297e+00,
        1.85237908e+00,  9.42454825e-01,  5.29451788e-01, -6.76540060e-01,
        3.38757284e-01,  4.16501997e-01,  1.07893415e+00,  2.83885871e-01,
        1.63989765e+00,  2.08231541e+00,  1.77174589e+00,  1.87743149e+00,
        1.93009169e+00,  2.00656433e+00,  1.73586154e+00,  1.84418248e+00,
        1.86491189e+00,  2.11404262e+00,  2.58750798e+00,  2.87441483e+00,
        2.90074736e+00,  2.40266574e+00,  2.71206299e+00,  2.03491370e+00,
        2.48193227e+00,  2.48104901e+00,  2.30028174e+00,  1.50018628e+00,
        2.52098293e+00,  2.31481781e+00,  3.03766613e+00,  2.21139653e+00,
        2.07036237e+00,  1.84984118e+00,  2.42541087e+00,  3.10049830e+00,
        3.40720442e+00,  2.31656203e+00,  2.92884607e+00,  2.30635210e+00,
        1.43087430e+00,  1.90955834e+00,  2.33873458e+00,  1.47165428e+00,
        1.72086040e+00,  6.78914604e-01,  1.16616574e+00,  9.95995858e-01,
       -4.97722869e-01, -2.73946193e-01, -4.52914235e-01, -4.76792752e-01,
        3.38837417e-01, -5.74222932e-01, -2.19394535e-01,  1.15299755e+00,
        4.93691395e-01, -6.42313767e-01, -1.65571783e-01,  2.81519552e-01,
       -1.99123064e-01, -3.22805726e-01, -9.39471389e-01, -6.21149557e-01,
       -1.76114765e-01,  1.89990149e-01,  1.06994656e+00,  1.64999017e+00,
        8.96119319e-01,  1.33045496e+00,  1.07926831e+00,  6.34437187e-01,
       -8.51598246e-01, -8.19828781e-01, -7.64788993e-01,  1.21043664e-01,
       -1.87149720e-01, -2.02969143e-01, -7.82372836e-01,  9.66644309e-01,
       -3.86555672e-01,  6.02303202e-01,  9.84266916e-01,  1.12236282e-01,
        2.71655081e-01,  4.87970063e-01,  7.06265255e-01,  7.84239901e-01,
        1.56914952e+00,  1.71204230e+00,  6.46331397e-01,  2.46733814e+00,
        2.11884593e+00,  1.36997694e+00,  1.43171001e+00,  9.24552220e-01,
       -3.06611733e-01,  1.96927621e+00,  5.42137477e-01,  2.27381019e+00,
        3.67532749e+00,  3.72096147e+00,  2.38351829e+00,  2.20443101e+00,
        3.59362401e+00,  1.84450088e+00,  2.63265025e+00,  2.38131415e+00,
        2.20085543e+00,  2.43478040e+00,  2.42340176e+00,  1.72009256e+00,
        2.01723344e+00,  1.37135926e+00,  9.84495185e-01,  7.75514982e-01,
        1.36385791e+00,  1.28979784e+00,  8.90843380e-01,  2.23675844e-01,
       -9.02525741e-01, -9.60768923e-01, -1.26353342e-01, -5.29998940e-01,
       -9.65543999e-02,  1.13932527e+00, -8.29809245e-01, -6.29611859e-01,
       -6.15270097e-01,  1.05547512e+00,  3.67622393e-01,  9.88708729e-01,
        2.22098946e+00,  2.10301356e+00,  7.66525046e-01,  1.20471832e+00,
        1.01076836e+00,  7.88676505e-01,  6.90400671e-01,  5.54675009e-01,
        3.42111772e-01, -4.23269826e-01,  6.01416767e-01,  1.04084635e+00,
        7.61451877e-01,  1.17648677e+00,  9.03350536e-01,  1.35375921e+00,
        1.01046715e+00,  1.25374400e+00,  1.58639464e+00,  1.44307518e+00,
        1.57438256e-01, -1.45714880e-01, -5.66031025e-01, -1.17696470e+00,
       -5.81298738e-01, -3.65449277e-01, -5.15244658e-01, -5.97082067e-01,
        5.39933445e-01,  3.44908109e-01,  1.10839555e+00,  8.73231345e-01,
        3.88514345e-01,  1.46377567e+00, -7.21994872e-01, -3.09340980e-01,
       -1.50223153e-01, -6.11635715e-01, -1.13881841e-01, -8.88605763e-01,
       -3.69299812e-01,  4.56593843e-01,  5.55315131e-01,  1.61024607e+00,
        2.42700998e+00,  2.26316212e+00,  2.03703908e+00,  2.71642266e+00,
        2.83599026e+00,  1.59324667e+00,  1.91717854e+00,  1.54790549e+00,
        1.04171075e+00,  9.44173198e-01,  1.12131486e+00,  1.85895466e+00,
        1.68763185e+00,  2.66145159e+00,  7.44668712e-01,  1.34938805e+00,
        1.60204793e+00,  1.83271246e+00,  1.07136198e+00,  1.32114298e+00,
        1.47415285e+00,  9.16005978e-01,  1.43178921e+00,  4.95187568e-01,
       -4.42157688e-02,  1.52806025e+00,  2.24736282e+00,  2.17721733e+00,
        2.31971026e+00,  2.45322015e+00,  2.34390993e+00,  1.99783339e+00,
        1.53968546e+00, -1.07844932e-01,  9.09560845e-02,  4.50691691e-01,
        1.08711461e+00, -2.85947808e-02,  2.14401869e+00,  7.93465819e-01,
        1.90740741e+00,  1.62415699e+00,  1.49902369e+00,  1.59247941e+00,
        1.48498764e+00,  8.38788271e-01,  1.06892281e+00,  1.05197391e+00,
        1.46406761e+00,  1.23836216e+00,  1.11943163e+00,  1.44135097e-01,
        9.67298595e-01,  4.48308769e-01,  4.52479538e-01,  1.22688356e-02,
        1.00925926e-01,  8.81997099e-01,  1.36977466e-01,  4.98272879e-01,
       -2.34133729e-01, -1.84928354e-01, -6.92444079e-01, -1.68763185e-01,
        4.23353905e-01,  6.97031800e-01,  1.82877027e-01,  3.17571212e-01,
        1.01776021e+00,  1.63421707e+00,  1.50828466e+00,  1.21673033e+00,
        5.55841347e-01,  1.50604181e+00,  5.15931189e-01,  8.25839609e-01,
        9.03826482e-01,  6.21618314e-01,  4.83933321e-01,  7.53044981e-01,
        7.53070183e-01,  1.62548511e+00,  1.35024489e+00,  1.22140864e+00,
        1.47226034e+00,  1.58010545e+00,  8.46261279e-01,  1.61479860e+00,
        2.29530163e+00,  1.61841287e+00,  1.82021358e+00,  1.25495273e+00,
        2.16170975e+00,  2.14374169e+00,  2.14928519e+00,  2.08061743e+00,
        1.73682664e+00,  2.36765584e+00,  1.67673158e+00,  2.89600872e+00,
        1.48997562e+00,  1.69569937e+00,  1.73528418e+00,  2.25369554e+00,
        2.30892439e+00,  2.49080421e+00,  2.53457816e+00,  9.86809296e-01,
        1.88578572e-01,  8.17078863e-01,  1.64691953e-01, -6.44658371e-01,
       -2.56676634e-01,  3.20495387e-01,  6.86526270e-01,  7.17843963e-02,
       -5.80968721e-01, -4.80148139e-01,  1.01289839e-01,  1.66987024e-01,
        3.80772047e-01,  7.46633884e-01,  5.11808107e-01,  4.40775286e-01,
        1.43511975e+00,  1.46058873e+00,  1.00744027e+00,  9.57871508e-01,
        9.82096992e-01,  2.99499324e-01,  1.54364448e+00,  1.90057269e+00,
        1.82133198e+00,  1.96939997e+00,  1.71740124e+00,  1.98533534e+00,
        2.27004608e+00,  2.09142296e+00,  9.67249294e-01,  1.39659299e+00,
        1.60789729e+00,  1.36464281e+00,  1.99688554e+00,  1.13866376e+00,
        4.30471633e-01,  6.80561754e-01,  5.01453069e-01,  7.89776982e-01,
        3.11582609e-01,  9.86028731e-01,  6.57076459e-01, -2.76125588e-01,
        1.54303350e-01,  3.70871274e-01, -5.80968721e-01,  5.14725920e-01,
        7.81043005e-01,  1.16157283e+00,  8.84765555e-01,  1.76403516e+00,
        1.15221153e+00,  5.94584816e-01,  7.63089380e-01,  2.54527702e-01,
        9.28875205e-01,  1.54370417e+00,  3.07386120e+00,  3.28585262e+00,
        2.89581224e+00,  3.17570431e+00,  2.68131504e+00,  1.50755672e+00,
        2.92446657e+00,  2.22924053e+00,  3.36115999e+00,  3.05220669e+00,
        1.44182298e+00,  9.88324345e-01,  1.54951590e+00,  1.03585079e+00,
        1.81672773e+00,  2.02801257e+00,  2.23543340e+00,  1.51518998e+00,
        9.32041877e-01,  9.78368819e-01,  1.76068858e+00,  1.97915495e+00,
        2.65063575e+00,  3.30542730e+00,  3.11218634e+00,  3.27234644e+00,
        3.73784491e+00,  3.67378802e+00,  3.30410435e+00,  3.41550653e+00,
        2.99554654e+00,  2.67438792e+00,  2.63125461e+00,  2.23435717e+00,
        2.46161370e+00,  2.45105684e+00,  2.53461102e+00,  2.69400128e+00,
        4.29188126e+00,  3.99353393e+00,  3.63696484e+00,  3.62520367e+00,
        2.38149965e+00,  1.62832672e+00,  1.61329828e+00,  1.48617655e+00,
        1.66146237e+00,  1.27035437e+00,  1.12494775e+00,  5.86025467e-01,
        1.88799784e+00,  1.77520315e+00,  1.53627862e+00,  7.82047124e-01,
        3.91379850e-01,  6.81644510e-01, -2.89647715e-01,  1.32200038e-01,
       -9.09107946e-02, -6.62170717e-02, -2.17777347e-01,  6.23378726e-01,
        1.76906818e+00,  1.44462906e+00,  1.32530270e+00,  4.56303498e-01,
        5.11213354e-01,  7.16883297e-01,  1.95052022e+00,  1.75679382e+00,
        8.75195490e-01,  8.93658869e-01,  8.67924528e-01,  8.63626479e-01,
        7.57936729e-01,  1.13168499e-01, -7.64322113e-01, -3.31666239e-01,
        3.20949782e-01,  7.81942246e-01,  3.71137366e-03, -3.79686252e-01,
        9.39046652e-02,  1.03730985e-01,  1.24879611e-01, -4.24446135e-01,
       -4.32488607e-01,  4.84411001e-01,  4.11213345e-01,  1.55416500e+00,
        1.25436302e+00,  4.15110949e-01,  1.15844036e+00, -8.24080063e-01,
        2.25074568e-02,  1.01786424e-01, -7.64998769e-02, -5.31209396e-01,
        1.73164313e-01,  1.17030626e+00,  6.75257472e-01,  5.32870169e-01,
        1.03062039e+00,  1.08841034e+00,  1.01053453e+00,  1.25575711e+00,
        4.07067961e-01,  3.07793506e-01,  1.20509805e+00,  1.16167632e+00,
        1.98212771e+00,  1.79846220e+00,  1.32415940e+00,  1.21673033e+00,
        1.34788707e+00,  1.28840623e+00,  1.12288448e+00]), ('wheretheressmoke', 'BLEU'): array([ 0.85245219,  1.11749447,  1.32775323,  1.30877313,  1.07135409,
        1.0369215 ,  1.0181035 ,  0.63796178,  0.22845554,  0.31338537,
        0.26616434,  1.16318581,  1.53178781,  2.34618962,  2.09645045,
        1.93168823,  1.61730049,  2.24137645,  1.44712516,  1.36004628,
        1.99715101,  1.72501623,  2.07368352,  1.66644785,  1.38586935,
        1.95706542,  1.63672948,  2.33311734,  1.74307515,  1.3550729 ,
        1.05152057,  2.27971977,  2.26526226,  2.39912442,  2.21298566,
        1.93023274,  1.70015718,  1.60161443,  1.14316348,  1.09067455,
        0.73330197,  0.95848744,  1.30206153,  1.77150807,  2.03863919,
        2.4301966 ,  2.61181902,  2.08531707,  1.92742912,  2.2735849 ,
        2.16756477,  1.63791469,  1.59728606,  0.62157441,  0.77033198,
        1.07905787,  0.9039975 ,  1.28702471,  1.27623491,  2.1887759 ,
        2.66826618,  2.76014246,  2.69566157,  1.44219241,  1.64730538,
        1.06332181,  1.19389876,  0.93900498,  0.57737451,  1.01973837,
        1.24902148,  0.37573299, -0.1658809 , -0.39885133, -0.35562079,
       -0.35562079, -0.35562079, -0.15110628, -0.66287188, -0.36080636,
       -0.73225203, -1.10148422, -0.46523119, -0.10841422, -0.78327589,
        0.02225522,  0.55437352,  0.8100809 ,  0.51521964,  1.14543608,
        1.56019685,  1.49626862,  1.43471848,  0.64168895,  0.31891522,
        0.48999611,  0.38949042,  0.38641637,  0.48803791, -0.07076132,
        0.83068494,  0.4685697 ,  0.43047163,  0.58811299,  0.06375228,
       -0.20341905, -0.03338135, -0.25110955,  0.5955334 ,  0.81658931,
        0.9251424 ,  0.67829132,  0.74546097,  0.9927694 ,  1.29224147,
        1.3770501 ,  1.27967176,  0.53240599,  0.91559456,  0.92941773,
        0.34312326,  0.52413557,  0.88004168,  1.31669757,  1.58654553,
        1.44726077,  0.90293718,  1.14621721,  1.43912349,  1.7042914 ,
        2.06907722,  1.59388867,  2.09397337,  1.74393307,  1.88883312,
        1.78179296,  1.80965524,  1.51496675,  1.8298798 ,  1.68927634,
        1.38463988,  1.29572643,  1.43933202,  1.27665248,  0.62260058,
        0.7116756 ,  0.45534779,  0.11333953,  0.46566149,  0.56809083,
        0.44580059,  0.81758743,  0.57163832,  0.99792793,  1.34855775,
        1.78118176,  1.82622122,  2.94227901,  3.01465396,  3.2826791 ,
        2.53014089,  2.60616189,  1.91888849,  1.82073295,  1.74174261,
        1.44837648,  1.39509294,  1.15140583,  1.05458489,  1.22814444,
        1.33166178,  0.89359181,  0.69217326,  0.5701045 ,  0.95693743,
        0.40434954, -0.64729778, -0.13956179, -0.22946217, -0.03227673,
        0.07188271,  1.41258637,  1.695987  ,  0.69941854,  0.95338067,
        0.81650065,  1.3536816 ,  1.4597863 ,  1.10803601,  1.27595573,
        1.60444953,  1.28754033,  1.13747358,  0.69615635,  1.13537985,
        1.22118051,  1.76811968,  1.28509818,  1.91399568,  2.21499972,
        2.99740881,  3.0768978 ,  3.07091223,  3.49826348,  2.65713746,
        1.68186354,  1.47244618,  1.09356964,  0.95045005,  0.40649541,
        0.00840692,  0.61196603,  0.73324149,  1.63617395,  1.72501563,
        1.68242331,  1.13812168,  0.68973049,  1.65072304,  2.282816  ,
        1.38684705,  2.61312346,  2.22237602,  2.59851832,  2.43922618,
        2.20080109,  1.48250995,  1.52956505,  0.81929652,  0.78927515,
        1.03618531,  1.15216901,  1.20458941,  1.94806214,  2.01575311,
        1.6       ,  2.26110489,  2.3819438 ,  2.40436676,  2.70527285,
        3.37146538,  2.25437941,  2.02763118,  1.84443196,  1.52095082,
        0.85138661,  1.08796379,  1.73787065,  1.9355463 ,  2.36137527,
        2.07560542,  1.81121031,  1.51174104,  1.67515812,  1.3542599 ,
        2.12527193,  1.73771057,  0.476005  , -0.11606501,  0.20694443,
       -0.16345302,  0.05177249,  0.10769533,  0.26375727, -0.47557308,
       -0.1177603 , -0.52951283, -0.19338562,  0.2840932 ,  0.04166667,
       -0.45534508,  0.28259479,  0.05501811,  0.31615962,  0.04691373,
       -0.25654458, -0.37354406, -0.03552903,  0.17624189,  0.76546476,
        0.47978086,  0.26898303,  0.48008657,  1.00059251,  0.91202294,
        0.8512095 ,  1.28062807,  0.80169147,  0.0266008 ,  0.03768315,
        0.27442474, -0.32539095,  0.2216463 ,  0.76498606,  0.9821996 ,
        1.01353006,  0.6364522 ,  0.5957261 ,  0.29560398,  0.50376951,
        0.94622555,  1.47032655,  1.7468434 ,  1.18527389,  1.25175535,
        1.12682641,  1.75918971,  1.73275632,  1.57700539,  1.67889394,
        1.63558601,  1.12275335,  0.62459544,  0.31448545,  0.84897172,
        1.19882912, -0.06276168, -0.50033785,  0.28765424,  0.88305972,
        1.0298008 ,  0.98647321,  1.16699351,  1.53357441,  2.26371178,
        2.68699816,  2.8243902 ,  2.27375282,  2.01882286,  2.20775667,
        2.0705526 ,  1.53363946,  1.32052721,  1.54577663,  0.56566585,
        0.0383695 ,  0.0204508 , -0.35508752, -0.76300645, -0.56269641,
       -0.84169451, -1.24772605, -0.87160092, -2.10991668, -1.39888074,
       -0.99967025,  0.27053082,  0.17360316,  0.62011167,  0.78928854,
        0.76992102,  1.38309413,  1.24293392,  1.47008354,  1.49208579,
        1.31642769,  2.06997139,  2.03783421,  2.09638237,  2.02396217,
        2.60161957,  2.86073243,  2.56526698,  1.9472898 ,  2.04036803,
        1.2109508 ,  1.14763258,  1.75415302,  2.26861134,  1.95565478,
        1.36165361,  1.53965125,  1.52318685,  0.94635976,  0.89717998,
        1.24401012,  0.72865242,  0.63255151,  0.88425952,  1.11051197,
        0.94675824,  0.96439804,  1.08529306,  0.74409539,  0.84007946,
        0.76895039,  0.85409274,  0.11894678,  0.09976121,  0.58141327,
        0.95260826,  1.36983319,  1.07713739,  0.77564395,  1.44990381,
        0.69776159,  0.92669613,  1.19907818,  0.69384901,  0.81338306,
        0.31590845,  1.12616063,  1.01789569,  1.03977485,  1.01636663,
        0.94156546,  0.24488653,  0.53641253,  0.20494715,  0.61926259,
        0.86232541,  0.95157229,  0.52333393,  0.9013864 ,  0.91256497,
        1.01625077,  1.0537265 ,  0.92443423,  0.95696068,  0.8340487 ,
        0.49099478,  0.76623609,  1.52272727,  1.80950069,  1.25239243,
        1.39390146,  1.35176208,  1.39794155,  0.00573759,  0.57991035,
        0.43959485,  0.23473661, -0.12512903,  0.03440138,  0.23522697,
        0.30390413,  0.13617029,  0.26787876, -0.14243198, -0.26255326,
        0.9473985 ,  1.12910555,  0.92549097,  0.74303362,  1.33187911,
        1.08121916,  0.86828305,  0.64560703,  0.87689163,  0.99033363,
        0.74141789,  1.40235936,  1.16922613,  1.79669015,  2.0160126 ,
        1.15901684,  0.56988165,  0.36967007,  0.55271768,  0.84603035,
        1.28497948,  1.39251556,  2.00118448,  1.98615357,  1.34149473,
        1.19689453,  1.22966592,  0.78450299,  1.11258782,  1.59859607,
        1.5669377 ,  2.21200682,  2.32063999,  2.89643613,  2.65295268,
        1.51981533,  1.59189776,  0.82920826,  0.48925087,  1.08846544,
        0.60117723,  0.15578584,  0.36060519,  0.51891514, -0.04465632,
       -0.17346185, -0.57514742,  0.02774568,  0.13673156, -0.57166903,
        0.51560093,  0.264818  , -0.26053694, -0.461674  , -0.09276727,
        0.11075242,  0.60240036,  0.64616234, -0.16065523, -0.71019543,
       -1.12072073, -0.81059963, -1.21538702, -0.79516211, -0.30392733,
       -0.38922273, -0.07774429, -0.09567735,  0.09735963, -0.60665455,
       -0.43261251, -0.84357469, -0.51201931, -0.67177768, -0.66634019,
       -1.39577296, -1.79093814, -1.29166667, -1.26072137, -1.0252304 ,
       -0.43527548,  0.77422882,  1.32499452,  1.53745666,  1.43582781,
        1.56156984,  1.25010518,  0.8869206 ,  0.5472465 , -0.22219788,
       -0.15368894,  0.20802447, -0.31383419,  0.15794336,  0.88322181,
        1.6746594 ,  2.16595833,  1.92655593,  1.89424852,  0.64601034,
        0.88787756,  0.49497551, -0.36060519,  0.18214402,  0.06796563,
        0.88642525,  0.9005386 ,  1.12061058,  1.45819287,  1.67849211,
        2.0599933 ,  2.55629849,  2.50481646,  2.69827809,  2.74429507,
        2.68713642,  2.17466473,  2.10215837,  2.5019058 ,  2.61984894,
        1.58228192,  1.48705202,  1.58700595]), ('wheretheressmoke', 'METEOR'): array([ 1.07152711,  1.25792354,  0.49022587,  1.52146173,  1.17519498,
        0.1537236 ,  0.17039409,  0.23628966,  0.16568262,  0.22113091,
        1.04835569,  0.59384301,  0.41317546,  1.17581809,  1.03859786,
        0.8678494 ,  0.78643883,  1.5130521 ,  1.05073866,  1.00172996,
        1.19607612,  1.21650809,  0.82823465,  1.56982916,  1.05478232,
        0.74024457,  0.02514682,  0.52782135,  0.32906773,  0.76115201,
        0.6504139 ,  1.04766814,  2.34071182,  2.44955751,  3.03353378,
        2.84523126,  3.19877646,  3.04846533,  2.24865326,  1.58988063,
        1.4151852 ,  1.50001979,  1.51440398,  1.99803353,  2.04877579,
        2.41067287,  2.69528293,  1.82640115,  1.67198022,  1.90113094,
        1.63916054,  1.25878542,  0.89907712,  0.08084757,  0.29559163,
        0.52934545,  0.46687922,  0.75803414,  0.74925079,  1.79208605,
        3.13423875,  3.23671913,  3.33469652,  2.68428294,  1.80408403,
        1.26729748,  1.28737094,  0.71031277,  0.52579234,  0.62095037,
        2.00298418,  1.23410313, -0.12196098, -0.74084893, -0.89178708,
       -0.89147331, -0.89138843, -0.58661465, -0.93217817, -0.93372915,

In [2]:
window_zscores = {'subject': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for subject in [1,2,3]:
    for task in ['wheretheressmoke']:
        scores = np.load(f'scores/S{subject}/perceived_speech/{task}.npz', allow_pickle=True)['window_zscores'].item()
        # print(scores['window_zscores'].item())
        window_zscores['subject'].append(subject)
        window_zscores['WER'].append(scores[(task, 'WER')])
        window_zscores['BLEU'].append(scores[(task, 'BLEU')])
        window_zscores['METEOR'].append(scores[(task, 'METEOR')])
        window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'subject': [1, 2, 3],
 'WER': [array([ 6.25055987e-01,  1.54919334e+00,  1.45774958e+00,  1.33936787e+00,
          1.69937152e+00,  1.61598135e+00,  2.00698861e+00,  1.73152978e+00,
          3.03979376e-01,  1.22500941e-01,  1.06644164e+00,  1.39585843e+00,
          1.81772642e+00,  1.52208010e+00,  9.74185538e-01,  1.04293630e+00,
          3.00865336e-01,  1.58554873e+00,  1.28073887e+00,  1.87501316e+00,
          1.86308593e+00,  7.68941313e-01,  8.31715849e-01,  1.14841431e+00,
          1.20650193e+00,  1.09089769e+00,  2.64386351e-01,  1.59810329e+00,
          1.19344456e+00,  1.62649485e+00,  1.43543122e+00,  1.58586736e+00,
          9.67986391e-01,  1.25797850e+00,  1.51289998e+00,  1.35976906e+00,
          1.68766392e+00,  1.35987570e+00,  9.37911840e-01,  1.17932485e+00,
          1.76532044e-01,  3.83123063e-01,  3.65392048e-02, -1.23869628e-15,
          1.62606351e-01,  1.31032835e+00,  1.10288853e+00,  6.97588692e-01,
          1.13346614e+00, -4.98630023e-01,  1.39808197e-01,  2.86038777e-01,
          1.25989658e+00,  9.65616396e-01,  2.37329370e+00,  3.01791061e+00,
          1.99054885e+00,  3.43849745e-01,  1.82559330e+00,  1.16367751e+00,
          2.52575390e+00,  1.87926046e+00,  2.61974748e+00,  1.28002090e+00,
          2.24397376e+00,  7.87769151e-01,  1.03090821e+00,  1.44460730e+00,
         -4.77387823e-01, -4.02801830e-01, -2.63285915e-01, -7.93361657e-01,
         -9.00949146e-01, -9.62606157e-01, -8.78142042e-01, -5.90828076e-01,
         -4.53413450e-01,  2.67302382e-01, -5.27397993e-01,  3.44799547e-01,
          8.49110463e-01,  5.46812908e-01,  8.36973951e-02, -3.54222886e-01,
          3.93189986e-01,  1.23098144e+00,  1.04584241e+00,  1.28975879e+00,
          1.11921405e+00,  1.98315562e+00,  2.37332110e+00,  1.96643815e+00,
          3.05390934e+00,  3.93415591e+00,  4.16787907e+00,  3.40612609e+00,
          3.56929658e+00,  3.78333855e+00,  2.67973795e+00,  1.02435811e+00,
          1.46381975e+00,  1.59424090e+00,  1.92011426e+00,  1.75228297e+00,
          1.85237908e+00,  9.42454825e-01,  5.29451788e-01, -6.76540060e-01,
          3.38757284e-01,  4.16501997e-01,  1.07893415e+00,  2.83885871e-01,
          1.63989765e+00,  2.08231541e+00,  1.77174589e+00,  1.87743149e+00,
          1.93009169e+00,  2.00656433e+00,  1.73586154e+00,  1.84418248e+00,
          1.86491189e+00,  2.11404262e+00,  2.58750798e+00,  2.87441483e+00,
          2.90074736e+00,  2.40266574e+00,  2.71206299e+00,  2.03491370e+00,
          2.48193227e+00,  2.48104901e+00,  2.30028174e+00,  1.50018628e+00,
          2.52098293e+00,  2.31481781e+00,  3.03766613e+00,  2.21139653e+00,
          2.07036237e+00,  1.84984118e+00,  2.42541087e+00,  3.10049830e+00,
          3.40720442e+00,  2.31656203e+00,  2.92884607e+00,  2.30635210e+00,
          1.43087430e+00,  1.90955834e+00,  2.33873458e+00,  1.47165428e+00,
          1.72086040e+00,  6.78914604e-01,  1.16616574e+00,  9.95995858e-01,
         -4.97722869e-01, -2.73946193e-01, -4.52914235e-01, -4.76792752e-01,
          3.38837417e-01, -5.74222932e-01, -2.19394535e-01,  1.15299755e+00,
          4.93691395e-01, -6.42313767e-01, -1.65571783e-01,  2.81519552e-01,
         -1.99123064e-01, -3.22805726e-01, -9.39471389e-01, -6.21149557e-01,
         -1.76114765e-01,  1.89990149e-01,  1.06994656e+00,  1.64999017e+00,
          8.96119319e-01,  1.33045496e+00,  1.07926831e+00,  6.34437187e-01,
         -8.51598246e-01, -8.19828781e-01, -7.64788993e-01,  1.21043664e-01,
         -1.87149720e-01, -2.02969143e-01, -7.82372836e-01,  9.66644309e-01,
         -3.86555672e-01,  6.02303202e-01,  9.84266916e-01,  1.12236282e-01,
          2.71655081e-01,  4.87970063e-01,  7.06265255e-01,  7.84239901e-01,
          1.56914952e+00,  1.71204230e+00,  6.46331397e-01,  2.46733814e+00,
          2.11884593e+00,  1.36997694e+00,  1.43171001e+00,  9.24552220e-01,
         -3.06611733e-01,  1.96927621e+00,  5.42137477e-01,  2.27381019e+00,
          3.67532749e+00,  3.72096147e+00,  2.38351829e+00,  2.20443101e+00,
          3.59362401e+00,  1.84450088e+00,  2.63265025e+00,  2.38131415e+00,
          2.20085543e+00,  2.43478040e+00,  2.42340176e+00,  1.72009256e+00,
          2.01723344e+00,  1.37135926e+00,  9.84495185e-01,  7.75514982e-01,
          1.36385791e+00,  1.28979784e+00,  8.90843380e-01,  2.23675844e-01,
         -9.02525741e-01, -9.60768923e-01, -1.26353342e-01, -5.29998940e-01,
         -9.65543999e-02,  1.13932527e+00, -8.29809245e-01, -6.29611859e-01,
         -6.15270097e-01,  1.05547512e+00,  3.67622393e-01,  9.88708729e-01,
          2.22098946e+00,  2.10301356e+00,  7.66525046e-01,  1.20471832e+00,
          1.01076836e+00,  7.88676505e-01,  6.90400671e-01,  5.54675009e-01,
          3.42111772e-01, -4.23269826e-01,  6.01416767e-01,  1.04084635e+00,
          7.61451877e-01,  1.17648677e+00,  9.03350536e-01,  1.35375921e+00,
          1.01046715e+00,  1.25374400e+00,  1.58639464e+00,  1.44307518e+00,
          1.57438256e-01, -1.45714880e-01, -5.66031025e-01, -1.17696470e+00,
         -5.81298738e-01, -3.65449277e-01, -5.15244658e-01, -5.97082067e-01,
          5.39933445e-01,  3.44908109e-01,  1.10839555e+00,  8.73231345e-01,
          3.88514345e-01,  1.46377567e+00, -7.21994872e-01, -3.09340980e-01,
         -1.50223153e-01, -6.11635715e-01, -1.13881841e-01, -8.88605763e-01,
         -3.69299812e-01,  4.56593843e-01,  5.55315131e-01,  1.61024607e+00,
          2.42700998e+00,  2.26316212e+00,  2.03703908e+00,  2.71642266e+00,
          2.83599026e+00,  1.59324667e+00,  1.91717854e+00,  1.54790549e+00,
          1.04171075e+00,  9.44173198e-01,  1.12131486e+00,  1.85895466e+00,
          1.68763185e+00,  2.66145159e+00,  7.44668712e-01,  1.34938805e+00,
          1.60204793e+00,  1.83271246e+00,  1.07136198e+00,  1.32114298e+00,
          1.47415285e+00,  9.16005978e-01,  1.43178921e+00,  4.95187568e-01,
         -4.42157688e-02,  1.52806025e+00,  2.24736282e+00,  2.17721733e+00,
          2.31971026e+00,  2.45322015e+00,  2.34390993e+00,  1.99783339e+00,
          1.53968546e+00, -1.07844932e-01,  9.09560845e-02,  4.50691691e-01,
          1.08711461e+00, -2.85947808e-02,  2.14401869e+00,  7.93465819e-01,
          1.90740741e+00,  1.62415699e+00,  1.49902369e+00,  1.59247941e+00,
          1.48498764e+00,  8.38788271e-01,  1.06892281e+00,  1.05197391e+00,
          1.46406761e+00,  1.23836216e+00,  1.11943163e+00,  1.44135097e-01,
          9.67298595e-01,  4.48308769e-01,  4.52479538e-01,  1.22688356e-02,
          1.00925926e-01,  8.81997099e-01,  1.36977466e-01,  4.98272879e-01,
         -2.34133729e-01, -1.84928354e-01, -6.92444079e-01, -1.68763185e-01,
          4.23353905e-01,  6.97031800e-01,  1.82877027e-01,  3.17571212e-01,
          1.01776021e+00,  1.63421707e+00,  1.50828466e+00,  1.21673033e+00,
          5.55841347e-01,  1.50604181e+00,  5.15931189e-01,  8.25839609e-01,
          9.03826482e-01,  6.21618314e-01,  4.83933321e-01,  7.53044981e-01,
          7.53070183e-01,  1.62548511e+00,  1.35024489e+00,  1.22140864e+00,
          1.47226034e+00,  1.58010545e+00,  8.46261279e-01,  1.61479860e+00,
          2.29530163e+00,  1.61841287e+00,  1.82021358e+00,  1.25495273e+00,
          2.16170975e+00,  2.14374169e+00,  2.14928519e+00,  2.08061743e+00,
          1.73682664e+00,  2.36765584e+00,  1.67673158e+00,  2.89600872e+00,
          1.48997562e+00,  1.69569937e+00,  1.73528418e+00,  2.25369554e+00,
          2.30892439e+00,  2.49080421e+00,  2.53457816e+00,  9.86809296e-01,
          1.88578572e-01,  8.17078863e-01,  1.64691953e-01, -6.44658371e-01,
         -2.56676634e-01,  3.20495387e-01,  6.86526270e-01,  7.17843963e-02,
         -5.80968721e-01, -4.80148139e-01,  1.01289839e-01,  1.66987024e-01,
          3.80772047e-01,  7.46633884e-01,  5.11808107e-01,  4.40775286e-01,
          1.43511975e+00,  1.46058873e+00,  1.00744027e+00,  9.57871508e-01,
          9.82096992e-01,  2.99499324e-01,  1.54364448e+00,  1.90057269e+00,
          1.82133198e+00,  1.96939997e+00,  1.71740124e+00,  1.98533534e+00,
          2.27004608e+00,  2.09142296e+00,  9.67249294e-01,  1.39659299e+00,
          1.60789729e+00,  1.36464281e+00,  1.99688554e+00,  1.13866376e+00,
          4.30471633e-01,  6.80561754e-01,  5.01453069e-01,  7.89776982e-01,
          3.11582609e-01,  9.86028731e-01,  6.57076459e-01, -2.76125588e-01,
          1.54303350e-01,  3.70871274e-01, -5.80968721e-01,  5.14725920e-01,
          7.81043005e-01,  1.16157283e+00,  8.84765555e-01,  1.76403516e+00,
          1.15221153e+00,  5.94584816e-01,  7.63089380e-01,  2.54527702e-01,
          9.28875205e-01,  1.54370417e+00,  3.07386120e+00,  3.28585262e+00,
          2.89581224e+00,  3.17570431e+00,  2.68131504e+00,  1.50755672e+00,
          2.92446657e+00,  2.22924053e+00,  3.36115999e+00,  3.05220669e+00,
          1.44182298e+00,  9.88324345e-01,  1.54951590e+00,  1.03585079e+00,
          1.81672773e+00,  2.02801257e+00,  2.23543340e+00,  1.51518998e+00,
          9.32041877e-01,  9.78368819e-01,  1.76068858e+00,  1.97915495e+00,
          2.65063575e+00,  3.30542730e+00,  3.11218634e+00,  3.27234644e+00,
          3.73784491e+00,  3.67378802e+00,  3.30410435e+00,  3.41550653e+00,
          2.99554654e+00,  2.67438792e+00,  2.63125461e+00,  2.23435717e+00,
          2.46161370e+00,  2.45105684e+00,  2.53461102e+00,  2.69400128e+00,
          4.29188126e+00,  3.99353393e+00,  3.63696484e+00,  3.62520367e+00,
          2.38149965e+00,  1.62832672e+00,  1.61329828e+00,  1.48617655e+00,
          1.66146237e+00,  1.27035437e+00,  1.12494775e+00,  5.86025467e-01,
          1.88799784e+00,  1.77520315e+00,  1.53627862e+00,  7.82047124e-01,
          3.91379850e-01,  6.81644510e-01, -2.89647715e-01,  1.32200038e-01,
         -9.09107946e-02, -6.62170717e-02, -2.17777347e-01,  6.23378726e-01,
          1.76906818e+00,  1.44462906e+00,  1.32530270e+00,  4.56303498e-01,
          5.11213354e-01,  7.16883297e-01,  1.95052022e+00,  1.75679382e+00,
          8.75195490e-01,  8.93658869e-01,  8.67924528e-01,  8.63626479e-01,
          7.57936729e-01,  1.13168499e-01, -7.64322113e-01, -3.31666239e-01,
          3.20949782e-01,  7.81942246e-01,  3.71137366e-03, -3.79686252e-01,
          9.39046652e-02,  1.03730985e-01,  1.24879611e-01, -4.24446135e-01,
         -4.32488607e-01,  4.84411001e-01,  4.11213345e-01,  1.55416500e+00,
          1.25436302e+00,  4.15110949e-01,  1.15844036e+00, -8.24080063e-01,
          2.25074568e-02,  1.01786424e-01, -7.64998769e-02, -5.31209396e-01,
          1.73164313e-01,  1.17030626e+00,  6.75257472e-01,  5.32870169e-01,
          1.03062039e+00,  1.08841034e+00,  1.01053453e+00,  1.25575711e+00,
          4.07067961e-01,  3.07793506e-01,  1.20509805e+00,  1.16167632e+00,
          1.98212771e+00,  1.79846220e+00,  1.32415940e+00,  1.21673033e+00,
          1.34788707e+00,  1.28840623e+00,  1.12288448e+00]),
  array([-2.05338088e-01,  2.96760343e-01, -3.19224201e-01, -4.85642931e-01,
          1.50515339e+00,  4.71123647e-01,  1.23066231e+00,  3.40107298e-01,
          6.06091527e-01,  6.84884940e-01,  5.13024682e-01,  1.06810349e+00,
          5.10914913e-01,  1.92212059e+00,  1.05826618e+00,  1.55029139e+00,
          2.04003906e+00,  1.59647889e+00,  1.94374818e+00,  1.81405322e+00,
          1.56914952e+00,  1.26137619e+00,  6.47380767e-01,  5.03626448e-01,
          1.13160689e+00,  4.18355091e-01,  6.70063462e-01,  2.02868712e-01,
          7.00100845e-01,  5.96841301e-01,  1.15092725e+00,  6.84268286e-01,
          8.20504934e-01, -3.90566733e-01,  1.12173428e+00,  3.88922234e-01,
          6.20700822e-01, -1.77819895e-01, -2.87361068e-02,  1.24792693e+00,
          1.24657714e+00,  1.52355906e+00,  1.19695880e+00,  1.66644171e+00,
          1.24623479e+00,  1.60361291e+00,  1.92997570e+00,  8.70773107e-01,
          1.02373105e+00, -1.89770821e-02,  3.90673185e-02,  4.63205396e-01,
         -2.23662720e-02,  7.65966470e-01,  4.83076287e-01,  4.94015094e-01,
          9.61731675e-01,  1.58679216e+00,  6.97833524e-01,  1.47851425e-01,
         -3.09512249e-01, -4.62381006e-01,  3.88210905e-01, -7.10666266e-01,
         -1.29919182e+00, -8.86451382e-01,  2.43185912e-01,  6.12056372e-01,
          1.58945102e-01, -2.85365073e-01,  1.05456341e+00, -7.48288719e-02,
          1.47308515e+00,  1.32872011e+00,  1.24366599e+00,  8.83079050e-01,
          1.13856222e+00,  3.07654489e-01,  1.10335821e+00,  1.08194464e+00,
          1.28670305e+00,  1.46857632e+00,  2.08291662e+00,  2.16120002e+00,
          1.48926915e+00,  4.48310854e-01, -2.40561558e-01, -1.78395523e-01,
          1.13065197e-01,  5.02379833e-01, -6.82901753e-01,  8.79685811e-01,
          4.92500013e-01,  2.53444533e-01,  5.53074504e-01, -4.72708547e-01,
          3.11163937e-01,  8.90906160e-03,  6.18088637e-01,  1.63896668e-01,
          8.03614375e-01,  1.55022074e+00,  1.64468216e+00,  1.48229851e+00,
          1.43626500e+00,  1.06133600e+00,  1.45815636e+00,  1.74328320e+00,
          1.46854239e+00,  2.14473964e+00,  2.87874215e+00,  2.97878654e+00,
          2.68668969e+00,  2.67808709e+00,  3.25329438e+00,  1.17050076e+00,
          2.46979029e+00,  3.40544220e+00,  2.24130179e+00,  2.20686838e+00,
          2.04398263e+00,  2.60820774e+00,  2.27286587e+00,  1.79489540e+00,
          1.80059534e+00,  1.95668319e+00,  1.34602568e+00,  1.60052104e+00,
          1.86329898e+00,  1.26200201e+00,  9.58943350e-01,  1.12240517e+00,
          1.13016066e-01, -2.74791590e-01,  1.17252769e+00, -4.31484000e-01,
         -4.29805566e-01, -6.49519053e-01, -4.34289432e-01, -7.97556277e-01,
          2.84880639e-01, -3.72662872e-01,  8.13907620e-01,  1.91713400e+00,
          2.03460071e+00,  1.78671962e+00,  1.25061620e+00,  1.24131652e+00,
          6.41005300e-01,  6.06767100e-01,  3.13292316e-01,  1.25075546e-01,
          1.17694143e+00, -3.12012887e-01, -3.80989750e-01, -4.96586540e-01,
          3.72219977e-01,  3.48155312e-01,  5.78314932e-02,  6.62180181e-01,
          8.75003697e-01,  2.97133452e-01,  5.78314932e-02, -1.98627212e-01,
          1.08394406e-01, -1.37482212e-01,  8.90906160e-03,  5.10386757e-01,
          8.91952975e-01,  1.27109006e+00,  1.19070054e+00,  1.91764034e+00,
          7.72539396e-01,  1.17853770e+00,  6.39101482e-01,  3.48027612e-01,
          5.93943142e-01,  5.45015483e-01, -1.79134205e-01,  8.98026510e-02,
         -2.02093355e-01, -1.47540174e-01,  4.59210327e-01,  7.11930907e-01,
          1.31949302e-01,  1.18778585e+00,  9.36585812e-01,  9.75234114e-01,
          1.34457982e+00,  6.04369611e-01,  1.80340019e+00,  7.43112557e-01,
          1.07304987e+00,  1.70296590e+00,  1.82102086e+00,  1.70175823e+00,
          1.42373699e+00,  1.67741263e+00,  1.59121263e+00,  2.45975741e+00,
          2.02679137e+00,  1.85967612e+00,  1.34879452e+00,  1.60063108e+00,
          2.00627157e+00,  2.14902783e+00,  1.01126407e+00,  7.21675466e-01,
          1.22886126e+00,  1.20857609e+00,  1.14328931e+00,  1.86429282e+00,
          2.45137046e+00,  1.96917739e+00,  1.52659197e+00,  2.22829071e+00,
          1.94168764e+00,  2.11490013e+00, -3.79663198e-01, -4.92835404e-01,
          8.72356744e-01,  1.78698665e+00,  9.45609353e-01,  6.76230624e-01,
          3.47579780e-01,  2.57541840e-01,  9.59215833e-01,  1.12716975e+00,
          7.33799386e-01,  6.65899641e-01, -4.46599209e-01, -1.66177573e-02,
         -3.24200294e-01,  1.27750177e+00,  2.39886475e-01,  8.59611613e-01,
          4.24650290e-01,  1.20418710e+00, -1.26632120e-01,  3.70515466e-01,
          2.06037971e-01,  8.14152342e-01,  8.11070187e-01,  5.36530564e-01,
          9.69539699e-01,  1.49979829e+00,  1.70627952e+00,  6.94941056e-01,
          2.73589245e-01,  8.31342016e-01,  6.51329885e-01,  1.31832757e+00,
          1.09438186e+00,  4.41736288e-01, -1.56027700e-01, -8.21952943e-01,
         -9.30664201e-01, -4.00389979e-01, -5.38894531e-01, -1.10071840e+00,
         -1.55073161e+00, -1.03647310e+00, -1.32758965e+00, -3.82765908e-01,
         -4.96042848e-02, -9.67166181e-01, -9.71237436e-01, -2.94936906e-01,
         -4.77823937e-03, -9.57400946e-01, -1.12267043e+00, -1.60240069e+00,
         -1.44721669e+00, -1.90329720e+00, -1.68911682e+00, -1.61666412e+00,
         -1.78495799e+00, -9.80673052e-01, -9.52061930e-01, -9.37573251e-01,
         -7.68205217e-01, -8.15557173e-01, -9.31553197e-01, -8.19738917e-01,
         -1.28107318e-01,  5.97611610e-01, -2.48264416e-01, -2.67955957e-02,
          1.76809392e-01,  1.29185188e-01,  1.69676316e+00,  2.72494767e+00,
          3.25764792e+00,  3.34431847e+00,  3.13154068e+00,  2.89531890e+00,
          3.23177953e+00,  3.13947550e+00,  2.41433280e+00,  2.34573866e+00,
          3.21162863e+00,  2.83216041e+00,  2.53740076e+00,  2.62080569e+00,
          1.26399070e+00,  1.93594277e+00,  1.58945176e+00,  2.32984136e+00,
          1.38207255e+00,  2.40098019e+00,  2.02839594e+00,  8.98026510e-01,
          9.81940818e-01,  1.62702726e-01, -7.71893218e-01,  9.81155781e-01,
          1.02073548e+00,  9.52154460e-01,  3.65337695e-01,  5.34430188e-01,
          7.29540575e-02, -8.50571966e-01, -6.52116192e-01, -6.30836791e-01,
          1.85089999e-02,  1.72760437e-01,  4.14718747e-01,  4.10433230e-01,
          8.70544389e-01,  5.22242382e-01,  5.45324158e-01,  4.08272591e-01,
          4.47671639e-01, -1.12746620e-01,  5.56886020e-01,  1.65577109e-01,
         -5.55338476e-01, -7.70581237e-01, -6.16497710e-01, -1.90727199e-02,
         -2.09383228e-01, -3.69427830e-01, -1.22793254e+00, -7.35135876e-01,
         -9.24337445e-01, -8.11620267e-01,  5.94916013e-01, -2.19934180e-01,
          5.75329510e-02, -3.93447783e-03, -1.63905488e-01,  1.50134426e-01,
         -4.12967588e-01,  9.46344291e-01,  1.39070396e+00,  1.88360140e+00,
          1.89299243e+00,  1.18910264e+00,  1.22909388e+00,  1.65315904e+00,
          2.58156271e+00,  1.78736205e+00,  2.13543085e+00,  1.21520053e+00,
          1.42702288e+00,  2.40076616e+00,  1.75103682e+00,  2.92358453e+00,
          2.68573190e+00,  2.71986753e+00,  2.29205621e+00,  3.07983080e+00,
          1.26694166e+00,  2.95863047e+00,  2.78191524e+00,  2.87183263e+00,
          2.54596508e+00,  1.75593768e+00,  2.38054438e+00,  2.70504491e+00,
          2.06495126e+00,  1.32379168e+00,  1.36954241e+00,  1.18289148e+00,
          1.84436967e+00,  1.20646613e+00,  1.08821438e+00,  3.55640765e-01,
          1.12568727e+00,  1.02759051e+00,  1.04788035e+00,  1.66399853e+00,
          6.53410263e-01,  3.03728370e-01, -1.53349710e-01,  2.36499233e-02,
          1.95073325e+00,  1.87173703e+00,  2.13567606e+00,  2.54174735e+00,
          1.97264831e+00,  1.32272869e+00,  1.71084516e+00,  2.41209076e+00,
          1.87726073e+00,  3.13108931e+00,  3.10547231e+00,  3.50596261e+00,
          3.89500313e+00,  3.87722491e+00,  3.04605874e+00,  2.55021882e+00,
          2.37078317e+00,  2.45779768e+00,  2.85071828e+00,  1.72031839e+00,
          2.67770985e+00,  1.98277783e+00,  2.05684913e+00,  1.80783599e+00,
          2.16160521e+00,  2.22601571e+00,  2.38054438e+00,  2.73589629e+00,
          2.08003908e+00,  2.52865612e+00,  2.12625166e+00,  2.45227321e+00,
          2.95878654e+00,  1.87918298e+00,  3.00171728e+00,  1.11683359e+00,
          8.78108499e-01,  3.61472190e-01,  1.08795891e+00,  5.65597057e-01,
         -7.26023761e-01,  1.12926278e+00,  1.38653667e+00,  1.27216169e+00,
          1.06845625e+00,  5.29599200e-01,  2.55687398e-02,  1.99365694e-01,
          1.43776478e-01,  5.86866707e-02, -2.44225840e-02,  4.07326062e-01,
          2.32283736e-01,  7.48819297e-02,  9.87022236e-01,  1.36618497e+00,
          2.14643737e+00,  2.07584802e+00,  2.31955988e+00,  2.60308240e+00,
          7.82300060e-01,  1.04183685e+00,  8.90919875e-01,  1.07599388e+00,
          1.79102297e+00,  2.00404521e+00,  1.07601821e+00,  1.69947589e+00,
          1.58353069e+00,  1.59370087e+00,  1.30370246e+00,  9.52500953e-01,
          1.12237997e+00,  1.52639622e+00,  1.80957782e+00,  1.85785443e+00,

In [3]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

563
563
563
=
1689

,subject,WER,BLEU,METEOR,BERT
0,1,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,2,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,3,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [4]:
results_df

,subject,WER,BLEU,METEOR,BERT
0,1,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,2,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,3,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [5]:
S1=np.array(results_df.loc[0, 'BERT']).mean()
S2=np.array(results_df.loc[1, 'BERT']).mean()
S3=np.array(results_df.loc[2, 'BERT']).mean()
to_file = pd.DataFrame({'subject':[1,2,3], 'significantly_decoded': [S1,S2,S3]})
to_file.to_csv('perceived_speech_percentages.csv', index=False)

to_file

   subject  significantly_decoded
0        1               0.619893
1        2               0.642984
2        3               0.808171

In [6]:
results = np.load('results/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

{'words': array(['she', 'said', 'she', ..., 'that', 'she', 'needs'],
       shape=(1589,), dtype='<U13'),
 'times': array([ 10.2,  10.6,  11. , ..., 591. , 591.4, 591.8], shape=(1589,))}